const fs = require('fs');
const path = 'C:/Users/Claude/scripts/supabase_migrate.sql';

function row(country, name, age, gender, nationality, bio, appearance, looking_for) {
  const esc = s => s.replace(/'/g, "''");
  return `('${country}','${esc(name)}',${age},'${gender}','${nationality}','${esc(bio)}','${esc(appearance)}','${looking_for}')`;
}

function insertBlock(country, label, rows) {
  return `\n-- ============================================================\n-- Profils fictifs -- ${label}\n-- ============================================================\ninsert into public.demo_pins (country,name,age,gender,nationality,bio,appearance,looking_for) values\n${rows.join(',\n')};\n`;
}

// ── FR ──────────────────────────────────────────────────────────────────────
const fr = [
  row('fr','Camille',24,'femme','FR',"Exploratrice solitaire, j'aime les cafés inconnus","Cheveux châtains, veste beige, sac à dos rouge",'hug'),
  row('fr','Jade',27,'femme','FR',"Voyageuse solo entre deux missions","Lunettes rondes, manteau kaki, baskets blanches",'hug'),
  row('fr','Léa',22,'femme','FR',"Étudiante en Erasmus, curieuse de tout","Tresse blonde, sweat gris, jean bleu",'french_kiss'),
  row('fr','Manon',31,'femme','FR',"Photographe de rue, toujours en mouvement","Casquette noire, veste en cuir, appareil photo",'hug'),
  row('fr','Inès',26,'femme','FR',"Backpackeuse entre deux continents","Cheveux bouclés, écharpe orange, boots marron",'french_kiss'),
  row('fr','Lucie',29,'femme','FR',"Solo depuis Bordeaux, ouverte aux rencontres vraies","Robe fleurie, sac bandoulière rouge",'hug'),
  row('fr','Noémie',34,'femme','FR',"Coach de voyage, passionnée de connexions humaines","Pull beige, lunettes soleil, cheveux courts",'french_kiss'),
  row('fr','Chloé',23,'femme','FR',"Interrail en solo, première fois seule","Bonnet rouge, sac à dos vert, air rêveur",'hug'),
  row('fr','Margaux',38,'femme','FR',"Consultante nomade entre Paris et Lisbonne","Blazer gris, cheveux noirs, carnet dans la main",'hug'),
  row('fr','Alice',25,'femme','FR',"Artiste en résidence, cherche l'inattendu","Béret coloré, longue veste, écharpe jaune",'french_kiss'),
  row('fr','Sarah',30,'femme','FR',"Infirmière en congé sabbatique","Queue-de-cheval, doudoune bleue, sac banane",'hug'),
  row('fr','Emma',28,'femme','FR',"Libraire voyageuse, toujours un livre à la main","Lunettes épaisses, trench beige, cheveux mi-longs",'hug'),
  row('fr','Zoé',33,'femme','FR',"Musicienne, guitare dans le dos","Veste jean, boots noires, sourire facile",'french_kiss'),
  row('fr','Mathilde',36,'femme','FR',"Architecte en vacances, yeux grands ouverts","Manteau blanc, cheveux attachés, carnet de croquis",'hug'),
  row('fr','Pauline',21,'femme','FR',"Lycéenne en voyage de fin d'études","Short jean, t-shirt rayé, baskets colorées",'hug'),
  row('fr','Aurélie',41,'femme','FR',"Mère solo qui reprend la route","Cheveux roux, veste légère, regard déterminé",'hug'),
  row('fr','Clara',27,'femme','FR',"Danseuse contemporaine de passage","Body noir, large pantalon, chignon haut",'french_kiss'),
  row('fr','Océane',24,'femme','FR',"Éco-voyageuse, sac de 7kg max","Vêtements neutres, chaussures de marche, sourire chaleureux",'hug'),
  row('fr','Charlotte',32,'femme','FR',"Journaliste pigiste en repérage","Trench olive, carnet jaune, cheveux courts",'french_kiss'),
  row('fr','Élise',29,'femme','FR',"Chercheuse en pause terrain, curieuse des gens","Pull col roulé gris, jean, lunettes dorées",'hug'),
  row('fr','Louise',26,'femme','FR',"Solo depuis Lyon, adore les marchés locaux","Panier en osier, robe légère, cheveux au vent",'hug'),
  row('fr','Anaïs',35,'femme','FR',"Yogini nomade, cherche le calme et la connexion","Legging coloré, sac souple, bague ethnique",'french_kiss'),
  row('fr','Victoire',23,'femme','FR',"Stagiaire internationale entre deux vols","Veste blazer, cheveux mi-longs, sourire timide",'hug'),
  row('fr','Juliette',40,'femme','FR',"Actrice de théâtre en tournée","Écharpe bordeaux, bottes à talon, sac velours",'french_kiss'),
  row('fr','Clémence',28,'femme','FR',"Randonneuse urbaine, jamais sans sa carte","Anorak vert, chaussures de rando, cheveux nattes",'hug'),
  row('fr','Diane',44,'femme','FR',"Médecin humanitaire entre deux missions","Cheveux poivre et sel, veste fonctionnelle, sourire fatigué mais sincère",'hug'),
  row('fr','Béatrice',52,'femme','FR',"Retraitée précoce qui explore l'Europe","Cheveux blancs, imperméable coloré, bonne humeur",'hug'),
  row('fr','Gabrielle',38,'femme','FR',"Directrice artistique en escapade","Look minimaliste, pochette design, cheveux courts",'french_kiss'),
  row('fr','Nathalie',46,'femme','FR',"Traductrice interprète en conférence","Tenue professionnelle légère, badges de congrès",'hug'),
  row('fr','Marion',33,'femme','FR',"Cuisinière passionnée en voyage culinaire","Tablier taché, carnet de recettes, sacoches de marché",'hug'),
  row('fr','Hélène',29,'femme','FR',"Biologiste marine en déplacement","Pull marin, jumelles, cheveux attachés",'french_kiss'),
  row('fr','Iris',25,'femme','FR',"Influenceuse voyage, plus discrète en vrai","Look soigné mais accessible, téléphone en permanence",'hug'),
  row('fr','Solène',31,'femme','FR',"Institutrice en vacances bien méritées","Robe légère, sac paille, lunettes de soleil",'hug'),
  row('fr','Laure',37,'femme','FR',"Consultante RH qui se demande pourquoi elle l'est","Tailleur décontracté, carnet Moleskine, air pensif",'french_kiss'),
  row('fr','Virginie',43,'femme','FR',"Avocate qui décompresse enfin","Lunettes chics, sac cuir, look chic-décontracté",'hug'),
  row('fr','Stéphanie',39,'femme','FR',"Coach de vie entre deux séances","Tenue sport-chic, sourire contagieux",'french_kiss'),
  row('fr','Delphine',48,'femme','FR',"Historienne de l'art en repérage de musées","Carnet illustré, lunettes vintage, foulard coloré",'hug'),
  row('fr','Anaëlle',22,'femme','FR',"Gap year après le bac, tout découvrir","Sac à dos énorme, baskets usées, curiosité infinie",'hug'),
  row('fr','Christelle',55,'femme','FR',"Grand-mère active qui voyage sans ses enfants","Cheveux gris élégants, appareil photo compact",'hug'),
  row('fr','Amandine',27,'femme','FR',"Ostéopathe itinérante, corps et âme en mouvement","Tenue ample, sac de praticien, mains sûres",'french_kiss'),
  row('fr','Isabelle',45,'femme','FR',"Directrice d'école en visite pédagogique","Sac professionnel, regard bienveillant, tenue sobre",'hug'),
  row('fr','Françoise',58,'femme','FR',"Retraitée dynamique, Europe en train","Cheveux courts élégants, imperméable pratique",'hug'),
  row('fr','Valérie',42,'femme','FR',"DRH qui découvre le slow travel","Valise soignée, air décontracté tout neuf pour elle",'french_kiss'),
  row('fr','Sandrine',36,'femme','FR',"Cheffe cuisinière en voyage d'inspiration","Blouse de cuisine pliée dans le sac, nez affiné",'hug'),
  row('fr','Corinne',50,'femme','FR',"Infirmière cadre qui prend enfin l'air","Tenue décontractée, montre médicale au poignet",'hug'),
  row('fr','Hugo',25,'homme','FR',"Baroudeur entre deux saisons, libre comme l'air","Pull marin, jean effiloché, cheveux en désordre",'hug'),
  row('fr','Tom',29,'homme','FR',"Développeur en workation, curieux des villes","T-shirt blanc, veste légère, sac à dos tech",'french_kiss'),
  row('fr','Lucas',23,'homme','FR',"Étudiant Erasmus, premier voyage solo","Sweat à capuche, jean slim, baskets rouges",'hug'),
  row('fr','Théo',32,'homme','FR',"Chef cuisinier en vacances forcées","Tablier de cuir, barbe courte, mains expressives",'french_kiss'),
  row('fr','Mathis',27,'homme','FR',"Photographe indépendant, partout et nulle part","Veste militaire, appareil autour du cou, lunettes soleil",'hug'),
  row('fr','Axel',34,'homme','FR',"Commercial qui en a marre des hôtels business","Costard froissé, valise trolley, cravate dans la poche",'hug'),
  row('fr','Raphaël',26,'homme','FR',"Musicien en tournée, cherche l'énergie des rencontres","Bonnet gris, guitare acoustique, veste en jean",'french_kiss'),
  row('fr','Baptiste',30,'homme','FR',"Surfeur entre deux spots","Short coloré, sweat délavé, cheveux salés",'hug'),
  row('fr','Antoine',22,'homme','FR',"Lycéen en road trip avec ses potes","T-shirt de concert, jean troué, énergie débordante",'french_kiss'),
  row('fr','Julien',38,'homme','FR',"Ingénieur en pause, redécouvrant la lenteur","Polo blanc, pantalon chino, montre simple",'hug'),
  row('fr','Nicolas',31,'homme','FR',"Journaliste de voyage, toujours en quête de l'histoire","Trench marron, carnet rouge, regard curieux",'hug'),
  row('fr','Pierre',44,'homme','FR',"Architecte qui voyage pour s'inspirer","Lunettes design, sac cuir, tenue sobre et élégante",'french_kiss'),
  row('fr','Guillaume',28,'homme','FR',"Trader digital, préfère les cafés aux bureaux","Mac sur les genoux, hoodie gris, AirPods",'hug'),
  row('fr','Sébastien',36,'homme','FR',"Guide de randonnée en vacances paradoxales","Chaussures de trail, polaire bleue, cartes topographiques",'hug'),
  row('fr','Clément',24,'homme','FR',"Graphiste freelance, dessinant partout","Tote bag avec crayons, veste colorée, cheveux mi-longs",'french_kiss'),
  row('fr','Florian',29,'homme','FR',"Kiné en pause méritée, détendu et ouvert","Pull over loose, jean, look décontracté",'hug'),
  row('fr','Romain',33,'homme','FR',"Comédien entre deux castings","Veste en laine, livre de poche, sourire charmeur",'french_kiss'),
  row('fr','Kevin',26,'homme','FR',"Steward en escale, 3h à tuer en ville","Uniforme bleu, valise cabine, air fatigué mais sympa",'hug'),
  row('fr','Adrien',41,'homme','FR',"Papa solo qui reprend goût à l'aventure","Veste outdoor, sac à dos fonctionnel, regard bienveillant",'hug'),
  row('fr','Marc',47,'homme','FR',"Commercial fatigué qui cherche un vrai moment","Costume froissé, cravate desserrée, regard sincère",'hug'),
  row('fr','Denis',53,'homme','FR',"Retraité actif, tour d'Europe en train","Chapeau de randonnée, sac fonctionnel, sourire ouvert",'hug'),
  row('fr','Patrick',60,'homme','FR',"Veuf qui redécouvre la vie à 60 ans","Veste propre, regard timide mais chaleureux",'hug'),
  row('fr','Stéphane',42,'homme','FR',"Architecte paysagiste, la nature dans les yeux","Chemise lin, carnets de terrain, montre analogique",'french_kiss'),
  row('fr','Christophe',38,'homme','FR',"Pompier en repos, calme et attentif","Physique athlétique, veste simple, regard posé",'hug'),
  row('fr','François',34,'homme','FR',"Chercheur CNRS en déplacement","Sac à dos plein de docs, veste académique, distrait sympa",'hug'),
  row('fr','Michel',57,'homme','FR',"Patron de PME qui voyage enfin pour lui","Look soigné décontracté, montre de qualité",'french_kiss'),
  row('fr','Olivier',45,'homme','FR',"Enseignant de lycée en voyage pédagogique personnel","Pull chiné, lunettes, livre en poche",'hug'),
  row('fr','Vincent',36,'homme','FR',"Kinésithérapeute sportif en compétition marathon","Tenue running, montre GPS, corps en forme",'hug'),
  row('fr','Laurent',49,'homme','FR',"Directeur photo de cinéma entre deux tournages","Veste technique, œil professionnel, discrétion",'french_kiss'),
  row('fr','Jacques',62,'homme','FR',"Retraité de l'éducation nationale en grand voyage","Sac à dos de qualité, guide Michelin, curiosité intacte",'hug'),
  row('fr','Bernard',55,'homme','FR',"Chef d'entreprise qui décompresse enfin","Look décontracté surprenant chez lui, vraiment heureux",'hug'),
  row('fr','Robert',48,'homme','FR',"Médecin généraliste en congrès international","Badge de congrès, sacoche médicale, regard rassurant",'french_kiss'),
  row('fr','Alex',27,'non-binaire','FR',"Artiste entre genres et frontières, libre","Tenue androgyne, bijoux ethniques, sourire malicieux",'hug'),
  row('fr','Sam',24,'non-binaire','FR',"Performer de rue en résidence artistique","Pantalon large, veste brodée, cheveux colorés",'french_kiss'),
  row('fr','Rémy',30,'non-binaire','FR',"Thérapeute holistique en voyage intérieur","Habit ample naturel, pierres au cou, paix dans les yeux",'hug'),
  row('fr','Lou',26,'non-binaire','FR',"Illustrateur·rice de passage, observe tout","Carnet de croquis, veste oversize, lunettes épaisses",'hug'),
  row('fr','Eli',28,'non-binaire','FR',"Militant·e culturel·le, toujours en mouvement","Sac en bandoulière, badges militants, regard vif",'french_kiss'),
  row('fr','Morgan',31,'non-binaire','FR',"Designer UX qui observe les usages humains","Tenue fluide, écouteurs stylés, regard analytique",'hug'),
  row('fr','Charlie',34,'non-binaire','FR',"Écrivain·e entre deux chapitres, carnet sur soi","Manteau large, stylo derrière l'oreille, sourire rêveur",'french_kiss'),
  row('fr','Jules',29,'non-binaire','FR',"Danseur·se contemporain·e en tournée européenne","Corps en mouvement même immobile, tenue souple",'hug'),
  row('fr','Noa',25,'non-binaire','FR',"Étudiant·e en genre et sexualités, curieux·se de tout","Look affirmé, badges, discussion fascinante garantie",'hug'),
  row('fr','Sasha',27,'non-binaire','FR',"Vidéaste documentariste, toujours une caméra","Veste technique, micro-cravate visible, regard attentif",'french_kiss'),
];

// ── IT ──────────────────────────────────────────────────────────────────────
const it = [
  row('it','Sofia',25,'femme','IT',"Studentessa in Erasmus, scopro l'Europa da sola","Capelli neri, giacca rossa, zaino verde",'hug'),
  row('it','Giulia',28,'femme','IT',"Fotografa freelance, sempre in movimento","Capelli castani, macchina foto al collo, jeans",'french_kiss'),
  row('it','Valentina',31,'femme','IT',"Architetta in viaggio d'ispirazione","Occhiali design, cappotto bianco, taccuino",'hug'),
  row('it','Chiara',24,'femme','IT',"Backpacker tra un treno e l'altro","Capelli lunghi, scarpe da trekking, sorriso aperto",'french_kiss'),
  row('it','Francesca',27,'femme','IT',"Giornalista in cerca di storie vere","Taccuino giallo, impermeabile verde, capelli mossi",'hug'),
  row('it','Martina',33,'femme','IT',"Medica in vacanza, finalmente libera","Capelli a coda, occhiali da sole, zaino medico",'hug'),
  row('it','Laura',29,'femme','IT',"Designer grafica nomade","Mac sotto il braccio, cuffie colorate, look minimal",'french_kiss'),
  row('it','Serena',22,'femme','IT',"Studentessa di lettere, prima avventura sola","Borsa di tela, libro in mano, aria curiosa",'hug'),
  row('it','Alessia',36,'femme','IT',"Chef in fuga dalla cucina per qualche giorno","Grembiule di cuoio, mani espressive, sorriso caldo",'french_kiss'),
  row('it','Elisa',30,'femme','IT',"Traduttrice simultanea in conferenza","Look professionale, badge al collo, aria concentrata",'hug'),
  row('it','Roberta',34,'femme','IT',"Biologa marina in trasferta","Maglione blu mare, binocolo, capelli raccolti",'hug'),
  row('it','Paola',38,'femme','IT',"Psicologa in viaggio di ricerca","Quaderno di appunti, sguardo attento, tono calmo",'french_kiss'),
  row('it','Monica',26,'femme','IT',"Ballerina classica in tournée","Capelli a chignon, borsa da danza, postura elegante",'hug'),
  row('it','Stefania',41,'femme','IT',"Manager HR che ha bisogno di staccare","Tailleur rilassato, trolley, sorriso stanco ma vero",'hug'),
  row('it','Giovanna',23,'femme','IT',"Gap year dopo la laurea, tutto è possibile","Zaino enorme, scarpe consunte, energia pura",'french_kiss'),
  row('it','Isabella',29,'femme','IT',"Stilista in cerca d'ispirazione per strada","Look ricercato, occhio critico ma simpatico, borse multiple",'hug'),
  row('it','Annalisa',32,'femme','IT',"Musicista jazz in giro per festival","Strumento in spalla, aria bohémien, sorriso facile",'french_kiss'),
  row('it','Cinzia',44,'femme','IT',"Avvocata in pausa meritata","Cappotto di qualità, borsetta elegante, occhiali firmati",'hug'),
  row('it','Daniela',37,'femme','IT',"Ricercatrice universitaria in convegno","Borsa piena di libri, sguardo acuto, jeans",'hug'),
  row('it','Silvia',25,'femme','IT',"Fotografa di moda in trasferta","Reflex al collo, look editoriale, capelli ossigenati",'french_kiss'),
  row('it','Federica',31,'femme','IT',"Farmacista in viaggio botanico","Borsa di campo, guanti da giardinaggio, aria serena",'hug'),
  row('it','Beatrice',28,'femme','IT',"Attrice di teatro in tournée estiva","Sciarpa bordeaux, stivali, borsa di velluto",'french_kiss'),
  row('it','Giorgia',24,'femme','IT',"Social media manager in workation","Laptop e telefono sempre in mano, caffè sempre pronto",'hug'),
  row('it','Adele',35,'femme','IT',"Sommelier in tour enogastronomico","Bicchiere da degustazione in borsa, aria competente",'hug'),
  row('it','Ilaria',27,'femme','IT',"Yogini nomade, cerca connessioni vere","Tappetino arrotolato, abiti naturali, serenità contagiosa",'french_kiss'),
  row('it','Cecilia',40,'femme','IT',"Nutrizionista che gira per mercati locali","Borsa di tela, lista della spesa, sorriso salutista",'hug'),
  row('it','Ornella',47,'femme','IT',"Ceramista in cerca di argille nuove","Mani sporche di argilla, grembiule, aria creativa",'hug'),
  row('it','Patrizia',53,'femme','IT',"Guida turistica in giorno libero","Passo sicuro, conoscenza totale della città, relax visibile",'french_kiss'),
  row('it','Elena',34,'femme','IT',"Trader online, ufficio ovunque ci sia WiFi","Laptop, caffè, look casual ma attento",'hug'),
  row('it','Rossana',29,'femme','IT',"Insegnante in viaggio formativo","Borsa piena di appunti, aria curiosa, domande infinite",'hug'),
  row('it','Valeria',36,'femme','IT',"Runner amatoriale in giro per maratone","Scarpe da corsa, orologio GPS, fisico allenato",'french_kiss'),
  row('it','Tiziana',42,'femme','IT',"Scrittrice di romanzi storici, cerca atmosfere","Vestito vintage, quaderno di note, aria assorta",'hug'),
  row('it','Pamela',31,'femme','IT',"Fisioterapista in congresso professionale","Zaino tecnico, tuta comoda, mani sicure",'hug'),
  row('it','Rossella',26,'femme','IT',"Visual artist in residenza internazionale","Capelli blu, vestiti senza macchie quasi, sguardo vivace",'french_kiss'),
  row('it','Agnese',23,'femme','IT',"Studentessa di lingue, parla tutto tranne l'inglese","Libro di frasi, sorriso aperto, aria giocosa",'hug'),
  row('it','Carla',45,'femme','IT',"Dirigente scolastica in visita educativa","Borsa professionale, sguardo benevolo, abbigliamento sobrio",'hug'),
  row('it','Renata',58,'femme','IT',"Pensionata dinamica, Europa in treno","Capelli corti eleganti, impermeabile pratico",'hug'),
  row('it','Assunta',50,'femme','IT',"Casalinga che finalmente viaggia per sé","Borsa ricamata, sguardo stupito dalla libertà",'hug'),
  row('it','Concetta',39,'femme','IT',"Avvocatessa che scopre il viaggio lento","Borsa di qualità, look rilassato insolito per lei",'french_kiss'),
  row('it','Rosaria',44,'femme','IT',"Medico di base in congresso internazionale","Badge del congresso, borsa medica, sguardo rassicurante",'hug'),
  row('it','Marco',26,'homme','IT',"Barman in vacanza, mischia ovunque","Camicia aperta, jeans bianchi, sorriso facile",'hug'),
  row('it','Luca',30,'homme','IT',"Fotoreporter, sempre in transito","Giacca militare, reflex pesante, sguardo curioso",'french_kiss'),
  row('it','Andrea',24,'homme','IT',"Ingegnere informatico in workation","Zaino tecnologico, cuffie, t-shirt tech",'hug'),
  row('it','Davide',33,'homme','IT',"Sommelier in giro per vigne","Naso raffinato, taccuino di degustazione, modi eleganti",'french_kiss'),
  row('it','Alessandro',28,'homme','IT',"Musicista rock tra un concerto e l'altro","Chitarra in spalla, giacca di pelle, aria vissuta",'hug'),
  row('it','Matteo',22,'homme','IT',"Studente in Erasmus, prima volta solo","Zaino universitario, entusiasmo contagioso",'hug'),
  row('it','Federico',36,'homme','IT',"Chef stellato in vacanza anonima","Abbigliamento casual, mani sicure, palato raffinato",'french_kiss'),
  row('it','Stefano',31,'homme','IT',"Giornalista sportivo in trasferta","Giubbotto reporter, taccuino, occhio rapido",'hug'),
  row('it','Riccardo',27,'homme','IT',"Grafico freelance, disegna ovunque","Borsa con matite, giacca colorata, capelli lunghi",'french_kiss'),
  row('it','Giorgio',40,'homme','IT',"Architetto in cerca d'ispirazione urbana","Occhiali da vista, cartella di disegni, passo curioso",'hug'),
  row('it','Roberto',45,'homme','IT',"Imprenditore che vuole staccare davvero","Look business-casual, orologio bello, sorriso raro ma vero",'hug'),
  row('it','Claudio',38,'homme','IT',"Regista di documentari sempre in giro","Giubbotto tecnico, microfono a clip visibile, sguardo attento",'french_kiss'),
  row('it','Emanuele',29,'homme','IT',"Personal trainer in vacanza meritata","Fisico atletico, abbigliamento sportivo, energia positiva",'hug'),
  row('it','Filippo',23,'homme','IT',"Artista di strada in residenza","Abiti colorati di vernice, borsa con tele, aria creativa",'french_kiss'),
  row('it','Simone',35,'homme','IT',"Medico di base che ricarica le pile","Felpa comoda, sguardo rassicurante, passo tranquillo",'hug'),
  row('it','Massimo',43,'homme','IT',"Direttore creativo tra due campagne","Look curato ma rilassato, portfolio sotto il braccio",'hug'),
  row('it','Pietro',26,'homme','IT',"Velista in terra ferma per qualche giorno","Felpa da vela, pelle abbronzata, mani forti",'french_kiss'),
  row('it','Lorenzo',32,'homme','IT',"Docente universitario in convegno internazionale","Giacca accademica, borsa di libri, aria distante-simpatica",'hug'),
  row('it','Nicola',29,'homme','IT',"Cuoco di strada, sempre in movimento","Grembiule da strada, valigia di spezie, buon umore",'french_kiss'),
  row('it','Giovanni',50,'homme','IT',"Padre solo che riscopre la libertà di viaggiare","Giubbotto pratico, sorriso aperto, sguardo sereno",'hug'),
  row('it','Loris',48,'homme','IT',"Pilota di linea in scalo di 8 ore","Uniforme sbottonata, valigia pilota, stanchezza elegante",'hug'),
  row('it','Bruno',55,'homme','IT',"Pensionato dinamico, Europa in treno","Cappello da viaggio, zaino leggero, passo sicuro",'hug'),
  row('it','Carlo',41,'homme','IT',"Ingegnere civile in sopralluogo","Casco in borsa, scarpe robuste, aria tecnica",'french_kiss'),
  row('it','Dario',37,'homme','IT',"Pasticcere in giro per fiere internazionali","Mani delicate, valigetta di attrezzi, naso fine",'hug'),
  row('it','Enzo',46,'homme','IT',"Pescatore sportivo in gita di cultura","Stivali di gomma, aria serena, voglia di parlare",'hug'),
  row('it','Fabio',34,'homme','IT',"Veterinario in conferenza scientifica","Zaino professionale, aria calma, ama tutti gli animali",'french_kiss'),
  row('it','Gerardo',29,'homme','IT',"Pompiere in riposo, calmo e rassicurante","Fisico solido, veste semplice, sguardo tranquillo",'hug'),
  row('it','Ivano',43,'homme','IT',"Direttore di marketing in fuga dal board","Completo rilassato, telefono spento quasi, sorriso vero",'hug'),
  row('it','Jacopo',27,'homme','IT',"Assistente di volo in scalo improvvisato","Uniforme, trolley cabin, aria leggermente jet-lagged",'french_kiss'),
  row('it','Leo',31,'homme','IT',"Cuoco specializzato in cucina di strada","Grembiule da campo, borsa di spezie, entusiasmo culinario",'hug'),
  row('it','Rio',27,'non-binaire','IT',"Artista performativo tra generi e confini","Abito androgino, gioielli etnici, sorriso malizioso",'hug'),
  row('it','Nico',24,'non-binaire','IT',"Musicista elettronica in tour europeo","Cuffie grandi, giacca tecnica, fare tranquillo",'french_kiss'),
  row('it','Fio',30,'non-binaire','IT',"Terapeuta olistica in viaggio interiore","Abito naturale ampio, pietre al collo, calma radiante",'hug'),
  row('it','Cami',26,'non-binaire','IT',"Illustratore·trice in residenza artistica","Taccuino di schizzi, giacca oversize, occhiali spessi",'hug'),
  row('it','Dani',28,'non-binaire','IT',"Attivista culturale sempre in movimento","Borsa a tracolla, spille militanti, sguardo vivace",'french_kiss'),
  row('it','Blake',29,'non-binaire','IT',"Performer di strada in residenza artistica","Pantaloni larghi, giacca ricamata, capelli colorati",'french_kiss'),
  row('it','Sae',25,'non-binaire','IT',"Danzatore·trice contemporaneo·a in tournée","Corpo sempre in movimento, abbigliamento ampio",'hug'),
  row('it','Feen',31,'non-binaire','IT',"Scrittore·trice di sceneggiature, osserva tutto","Cappotto largo, penna dietro l'orecchio, sorriso sognante",'hug'),
  row('it','Zef',33,'non-binaire','IT',"Compositore·trice elettronica tra live set","Cuffie studio, giacca tecnica, passo ritmato",'french_kiss'),
  row('it','Miro',27,'non-binaire','IT',"Videomaker documentarista","Giacca tecnica, microfono a clip, sguardo attento",'hug'),
];

// ── DE ──────────────────────────────────────────────────────────────────────
const de = [
  row('de','Anna',26,'femme','DE',"Alleinreisende zwischen zwei Projekten, offen für echte Begegnungen","Braune Haare, rote Jacke, Wanderrucksack",'hug'),
  row('de','Sophie',29,'femme','DE',"Fotografin auf Städtereise","Kamera um den Hals, Jeans, neugieriger Blick",'french_kiss'),
  row('de','Julia',24,'femme','DE',"Erasmus-Studentin auf Entdeckungsreise","Blondes Haar, Uni-Hoodie, bunte Turnschuhe",'hug'),
  row('de','Lena',32,'femme','DE',"Architektin auf der Suche nach Inspiration","Designerbrille, weißer Mantel, Skizzenbuch",'french_kiss'),
  row('de','Marie',27,'femme','DE',"Krankenschwester im wohlverdienten Urlaub","Sportlicher Look, Rucksack, entspanntes Lächeln",'hug'),
  row('de','Laura',31,'femme','DE',"Journalistin auf Recherche","Grüner Trenchcoat, gelbes Notizbuch, lockige Haare",'hug'),
  row('de','Nina',23,'femme','DE',"Gap Year nach dem Abitur, alles entdecken","Riesiger Rucksack, abgenutzte Schuhe, pure Energie",'french_kiss'),
  row('de','Mia',28,'femme','DE',"Designerin im Workation-Modus","MacBook, Kopfhörer, minimalistischer Look",'hug'),
  row('de','Clara',34,'femme','DE',"Ärztin auf Forschungsreise","Funktionale Tasche, aufmerksamer Blick, ruhige Art",'hug'),
  row('de','Hannah',25,'femme','DE',"Musikerin auf Tour","Instrument auf dem Rücken, Bohème-Look, leichtes Lächeln",'french_kiss'),
  row('de','Sarah',30,'femme','DE',"Marketing-Managerin auf der Flucht vor Excel","Blazer gelockert, Trolley, echtes Lächeln",'hug'),
  row('de','Emma',36,'femme','DE',"Yogalehrerin auf spiritueller Reise","Naturfarbene Kleidung, Yoga-Matte, Gelassenheit",'hug'),
  row('de','Lisa',22,'femme','DE',"Studentin der Kunstgeschichte, erstes Solo-Abenteuer","Kunstbuch, Vintage-Brille, stilles Staunen",'french_kiss'),
  row('de','Leonie',29,'femme','DE',"Therapeutin zwischen zwei Seminaren","Weiche Kleidung, Heilsteine, sanfte Energie",'hug'),
  row('de','Katharina',35,'femme','DE',"Filmregisseurin beim Motiv-Scouting","Technische Weste, Klemmbrett, scharfer Blick",'french_kiss'),
  row('de','Stefanie',40,'femme','DE',"Unternehmensberaterin, die endlich abschaltet","Geknitterter Blazer, Reisekoffer, echter Erschöpfung",'hug'),
  row('de','Tanja',26,'femme','DE',"Tänzerin auf Europatournée","Stets in Bewegung, weite Hose, Chignon",'hug'),
  row('de','Verena',33,'femme','DE',"Biologin auf Feldforschung","Feldausrüstung, Fernglas, Haare zum Zopf gebunden",'french_kiss'),
  row('de','Kerstin',38,'femme','DE',"Rechtsanwältin im wohlverdienten Urlaub","Eleganter, aber entspannter Look, Ledertasche",'hug'),
  row('de','Melanie',27,'femme','DE',"Entwicklungshelferin zwischen zwei Einsätzen","Funktionale Kleidung, Armbänder aus aller Welt",'hug'),
  row('de','Petra',44,'femme','DE',"Gymnasiallehrerin auf Bildungsreise","Strickpullover, Notizblock, wacher Geist",'french_kiss'),
  row('de','Anja',31,'femme','DE',"Sommelière auf Weinreise","Degustation Taschenbuch, elegante aber praktische Kleidung",'hug'),
  row('de','Claudia',37,'femme','DE',"Stadtplanerin für neues Projekt unterwegs","Technische Karte, Stift hinter dem Ohr, nachdenklicher Blick",'hug'),
  row('de','Monika',48,'femme','DE',"Früh in Rente und Europa erkunden","Graues Haar elegant, bunter Regenmantel, gute Laune",'french_kiss'),
  row('de','Sabine',52,'femme','DE',"Schriftstellerin auf der Suche nach Material","Weiter Mantel, Stift immer dabei, beobachtend",'hug'),
  row('de','Helga',49,'femme','DE',"Lehrerin auf Erkundungsreise","Praktischer Rucksack, Notizbuch, wissbegieriger Blick",'hug'),
  row('de','Brigitte',57,'femme','DE',"Großmutter auf Europareise, ohne die Kinder","Elegant graues Haar, kompakte Kamera, beste Stimmung",'hug'),
  row('de','Gisela',43,'femme','DE',"Sozialarbeiterin erholt sich endlich","Bequeme Kleidung, warmes Lächeln, ruhige Präsenz",'hug'),
  row('de','Heike',35,'femme','DE',"Umweltingenieurin auf Nachhaltigkeitskonferenz","Öko-Kleidung, Metalltrinkflasche, grüne Überzeugungen",'french_kiss'),
  row('de','Dagmar',39,'femme','DE',"Ernährungsberaterin auf Marktbesuch","Leinentasche, Einkaufsliste, gesundheitsbegeistertes Lächeln",'hug'),
  row('de','Gudrun',46,'femme','DE',"Keramikerin auf der Suche nach neuen Tonerden","Lehmverschmierte Hände, Schürze, kreative Aura",'hug'),
  row('de','Renate',51,'femme','DE',"Hobbysportlerin und Freiheit-Suchende","Laufschuhe, GPS-Uhr, trainierter Körper",'french_kiss'),
  row('de','Meike',28,'femme','DE',"Social-Media-Fotografin, diskreter als gedacht","Gepflegtes, zugängliches Aussehen, Handy immer dabei",'hug'),
  row('de','Hannelore',54,'femme','DE',"Pensionärin die endlich alleine reist","Elegantes graues Haar, praktische Tasche, Neugier",'hug'),
  row('de','Friederike',33,'femme','DE',"Politikwissenschaftlerin auf Kongress","Aktentasche, Brille, nachdenklicher Blick",'french_kiss'),
  row('de','Ingrid',47,'femme','DE',"Ärztin im Sabbatical, neugierig auf alles","Sportlich-eleganter Look, Wanderstöcke",'hug'),
  row('de','Rosemarie',60,'femme','DE',"Witwe die das Reisen wiederzuentdeckt","Elegante weiße Haare, warmes Lächeln, Neugier pur",'hug'),
  row('de','Hildegard',55,'femme','DE',"Pensionierte Lehrerin auf Abenteuerreise","Wanderschuhe, Reiseführer, unendliche Energie",'hug'),
  row('de','Waltraud',42,'femme','DE',"Unternehmerin die sich eine Pause gönnt","Eleganter Freizeitlook, schöne Uhr, seltenes echtes Lächeln",'french_kiss'),
  row('de','Karoline',27,'femme','DE',"Doktorandin zwischen zwei Experimenten","Labortasche, Notizbuch, zerstreuter Charme",'hug'),
  row('de','Bettina',36,'femme','DE',"Grafikdesignerin die analoge Welt erkundet","Skizzenbuch, bunte Stifte, kreativer Blick",'hug'),
  row('de','Max',27,'homme','DE',"Backpacker zwischen Saison und Saison, frei wie der Wind","Marineblauer Pullover, ausgefranste Jeans, zerzaustes Haar",'hug'),
  row('de','Felix',30,'homme','DE',"IT-Entwickler im Workation","Weißes T-Shirt, leichte Jacke, Tech-Rucksack",'french_kiss'),
  row('de','Leon',24,'homme','DE',"Erasmus-Student, erste Solo-Reise","Kapuzenpullover, enge Jeans, rote Sneaker",'hug'),
  row('de','Lukas',33,'homme','DE',"Fotoreporter, immer unterwegs","Militärjacke, Kamera, Sonnenbrille",'french_kiss'),
  row('de','Jan',28,'homme','DE',"Musiker auf Tournée, sucht Energie","Graue Mütze, Akustikgitarre, Lederjacke",'hug'),
  row('de','Patrick',35,'homme','DE',"Ingenieur im Projekturlaub","Poloshirt, Chino, schlichte Uhr",'hug'),
  row('de','Tobias',22,'homme','DE',"Schüler auf Abschlussreise","Konzert-T-Shirt, zerrissene Jeans, überbordende Energie",'french_kiss'),
  row('de','Fabian',38,'homme','DE',"Spitzenkoch im anonymen Urlaub","Freizeitkleidung, sichere Hände, feiner Gaumen",'hug'),
  row('de','Niklas',31,'homme','DE',"Sportjournalist auf Auslandsreise","Reporter-Weste, Notizblock, schneller Blick",'hug'),
  row('de','Sven',29,'homme','DE',"Grafiker auf Selbstständigkeit","Farbenfroh, Tasche mit Bleistiften, langes Haar",'french_kiss'),
  row('de','Moritz',40,'homme','DE',"Architekt auf der Suche nach Inspiration","Designerbrille, Zeichenmappe, neugieriger Schritt",'hug'),
  row('de','Stefan',45,'homme','DE',"Unternehmer, der wirklich abschalten möchte","Business-Casual, schöne Uhr, seltenes aber echtes Lächeln",'hug'),
  row('de','Christian',26,'homme','DE',"Straßenkünstler in Kunstresidenzen","Farbbespritzte Kleidung, Leinwand, kreative Aura",'french_kiss'),
  row('de','Michael',48,'homme','DE',"Manager, der endlich für sich selbst reist","Gepflegter Freizeitlook, Qualitätsuhr",'hug'),
  row('de','Thomas',34,'homme','DE',"Forscher auf Auslandskonferenz","Prallgefüllter Rucksack, akademische Jacke, zerstreuter Charme",'hug'),
  row('de','Johannes',36,'homme','DE',"Naturführer im paradoxen Urlaub","Trailschuhe, blaues Fleece, topografische Karten",'french_kiss'),
  row('de','Peter',42,'homme','DE',"Dokumentarfilmer immer unterwegs","Technische Weste, sichtbares Ansteckmikrofon, aufmerksamer Blick",'hug'),
  row('de','David',27,'homme','DE',"Kinematurge zwischen zwei Drehs","Wollmantel, Taschenbuch, charmantes Lächeln",'french_kiss'),
  row('de','Kevin',29,'homme','DE',"Steward auf Zwischenstopp, 4 Stunden Zeit","Uniform, Handgepäck, leicht übermüdet, aber sympathisch",'hug'),
  row('de','Sebastian',44,'homme','DE',"Alleinreisender Vater, der das Abenteuer wieder entdeckt","Outdoor-Jacke, funktionaler Rucksack, wohlwollender Blick",'hug'),
  row('de','Ingo',53,'homme','DE',"Rentner, der Europa per Zug erkundet","Reisehut, leichter Rucksack, sicherer Schritt",'hug'),
  row('de','Werner',60,'homme','DE',"Witwer, der das Leben mit 60 neu entdeckt","Gepflegte Jacke, schüchterner aber herzlicher Blick",'hug'),
  row('de','Bernd',47,'homme','DE',"Handwerksmeister auf Bildungsreise","Robuste Schuhe, Arbeitstasche, offenes Lächeln",'hug'),
  row('de','Horst',55,'homme','DE',"Ruheständler, der Freiheit wieder spürt","Helle Hose, bequeme Schuhe, Zeit ohne Ende",'french_kiss'),
  row('de','Rainer',38,'homme','DE',"Softwareentwickler zwischen zwei Projekten","Laptop-Rucksack, T-Shirt, entspannter Blick",'hug'),
  row('de','Günther',50,'homme','DE',"Kaufmann der endlich allein reist","Gepflegter Freizeitlook, Qualitätsuhr",'hug'),
  row('de','Klaus',43,'homme','DE',"Ingenieur auf Messe zwischen zwei Terminen","Namensbadge, praktischer Anzug, freundlicher Blick",'french_kiss'),
  row('de','Helmut',57,'homme','DE',"Pensionierter Beamter auf Weltreise","Reisehut, Karte, stoisches Lächeln",'hug'),
  row('de','Walter',62,'homme','DE',"Rentner der die Freiheit neu entdeckt","Bequeme Kleidung, Kamera, strahlende Augen",'hug'),
  row('de','Kim',26,'non-binaire','DE',"Kunstperformer zwischen Genres und Grenzen","Androgynes Outfit, ethnischer Schmuck, schelmisches Lächeln",'hug'),
  row('de','Sam',24,'non-binaire','DE',"Straßenperformer in Kunstresidenzen","Weite Hose, besticktes Jackett, bunte Haare",'french_kiss'),
  row('de','Remy',31,'non-binaire','DE',"Ganzheitlicher Therapeut auf innerer Reise","Weites, natürliches Gewand, Steine am Hals, Frieden in den Augen",'hug'),
  row('de','Lou',28,'non-binaire','DE',"Illustrator auf Durchreise, beobachtet alles","Skizzenbuch, oversized Jacke, dicke Brille",'hug'),
  row('de','Robin',30,'non-binaire','DE',"Kulturaktivist, immer in Bewegung","Umhängetasche, Anstecker, wacher Blick",'french_kiss'),
  row('de','Lenn',27,'non-binaire','DE',"Elektronischer Musiker auf Europatournée","Große Kopfhörer, Technojacke, ruhige Ausstrahlung",'hug'),
  row('de','Ash',25,'non-binaire','DE',"Zeitgenössischer Tänzer auf Tour","Immer in Bewegung, lockere Kleidung",'french_kiss'),
  row('de','Fern',32,'non-binaire','DE',"Drehbuchautor, beobachtet alles","Großer Mantel, Stift hinter dem Ohr, versponnenes Lächeln",'hug'),
  row('de','Zola',34,'non-binaire','DE',"Elektronischer Komponist zwischen Live-Sets","Studio-Kopfhörer, Technojacke, rhythmischer Schritt",'french_kiss'),
  row('de','Marlo',28,'non-binaire','DE',"Dokumentarischer Videofilmer","Technische Jacke, sichtbares Lavaliermikrofon, aufmerksamer Blick",'hug'),
];

// ── ES ──────────────────────────────────────────────────────────────────────
const es = [
  row('es','Carmen',25,'femme','ES',"Mochilera entre trenes, siempre en movimiento","Pelo negro, chaqueta roja, mochila verde",'hug'),
  row('es','Lucía',28,'femme','ES',"Fotógrafa freelance, siempre de paso","Pelo castaño, cámara al cuello, vaqueros",'french_kiss'),
  row('es','Sofía',31,'femme','ES',"Arquitecta en viaje de inspiración","Gafas de diseño, abrigo blanco, cuaderno",'hug'),
  row('es','Isabel',24,'femme','ES',"Estudiante Erasmus, descubriendo Europa","Pelo largo, mochila universitaria, zapatillas de colores",'french_kiss'),
  row('es','Nuria',27,'femme','ES',"Periodista buscando historias reales","Cuaderno amarillo, impermeable verde, rizado",'hug'),
  row('es','Marta',33,'femme','ES',"Médica en sus merecidas vacaciones","Look deportivo, mochila, sonrisa desahogada",'hug'),
  row('es','Ana',29,'femme','ES',"Diseñadora gráfica en modo nómada","Mac bajo el brazo, auriculares de colores, look mínimal",'french_kiss'),
  row('es','Cristina',22,'femme','ES',"Gap year tras la selectividad, descubrirlo todo","Mochila enorme, zapatillas desgastadas, energía infinita",'hug'),
  row('es','Elena',36,'femme','ES',"Traductora en conferencia internacional","Look profesional, acreditación al cuello, concentrada",'hug'),
  row('es','Laura',30,'femme','ES',"Bióloga marina en trasfondo de investigación","Jersey azul marino, prismáticos, pelo recogido",'french_kiss'),
  row('es','Raquel',34,'femme','ES',"Psicóloga en viaje de investigación","Cuaderno, mirada atenta, tono calmado",'hug'),
  row('es','Pilar',38,'femme','ES',"Bailaora flamenca de gira","Vestido de lunares, moño alto, porte elegante",'hug'),
  row('es','Mercedes',41,'femme','ES',"Directora RRHH que necesita desconectar","Traje relajado, trolley, sonrisa cansada pero sincera",'french_kiss'),
  row('es','Rocío',23,'femme','ES',"Después de la uni, el mundo entero","Mochila enorme, entusiasmo sin límites",'hug'),
  row('es','Paula',29,'femme','ES',"Estilista buscando inspiración en la calle","Look cuidado, ojo crítico pero amable, múltiples bolsos",'hug'),
  row('es','Rosa',32,'femme','ES',"Músico de jazz de festival en festival","Instrumento al hombro, aire bohemio, sonrisa fácil",'french_kiss'),
  row('es','Inés',44,'femme','ES',"Abogada en merecido descanso","Abrigo de calidad, bolso elegante, gafas de marca",'hug'),
  row('es','María',37,'femme','ES',"Investigadora universitaria en congreso","Bolsa llena de libros, mirada aguda, vaqueros",'hug'),
  row('es','Silvia',25,'femme','ES',"Fotógrafa de moda en trasfondo","Réflex al cuello, look editorial, pelo rubio oxigenado",'french_kiss'),
  row('es','Noelia',31,'femme','ES',"Farmacéutica en viaje botánico","Bolsa de campo, guantes de jardinero, aire sereno",'hug'),
  row('es','Beatriz',28,'femme','ES',"Actriz de teatro de gira de verano","Bufanda burdeos, botas, bolso de terciopelo",'french_kiss'),
  row('es','Diana',24,'femme','ES',"Community manager en workation","Portátil y móvil siempre a mano, café siempre listo",'hug'),
  row('es','Adriana',35,'femme','ES',"Sommelier en tour enogastronómico","Copa de cata en el bolso, aire competente",'hug'),
  row('es','Rebeca',27,'femme','ES',"Yoguini nómada, busca conexiones reales","Esterilla enrollada, ropa natural, serenidad contagiosa",'french_kiss'),
  row('es','Consuelo',40,'femme','ES',"Cocinera apasionada de viaje culinario","Delantal manchado, cuaderno de recetas, alforjas del mercado",'hug'),
  row('es','Patricia',44,'femme','ES',"Directora de escuela en visita pedagógica","Bolsa profesional, mirada benévola, ropa sobria",'hug'),
  row('es','Francisca',58,'femme','ES',"Jubilada dinámica, Europa en tren","Pelo corto elegante, impermeable práctico",'hug'),
  row('es','Dolores',50,'femme','ES',"Ama de casa que por fin viaja sola","Bolsa bordada, mirada asombrada por la libertad",'hug'),
  row('es','Amparo',39,'femme','ES',"Abogada que descubre el viaje lento","Bolso de calidad, look relajado inusual para ella",'french_kiss'),
  row('es','Rosario',44,'femme','ES',"Médico de cabecera en congreso internacional","Acreditación, maletín médico, mirada tranquilizadora",'hug'),
  row('es','Encarnación',47,'femme','ES',"Ceramista buscando nuevas arcillas","Manos sucias de arcilla, delantal, aura creativa",'hug'),
  row('es','Esperanza',53,'femme','ES',"Guía turística en día libre","Paso seguro, conocimiento total de la ciudad, relax visible",'french_kiss'),
  row('es','Concepción',36,'femme','ES',"Corredora amateur por maratones","Zapatillas de running, reloj GPS, físico entrenado",'hug'),
  row('es','Virtudes',42,'femme','ES',"Escritora de novelas históricas, busca atmósferas","Vestido vintage, cuaderno de notas, aire absorto",'hug'),
  row('es','Remedios',31,'femme','ES',"Fisioterapeuta en congreso profesional","Mochila técnica, chándal cómodo, manos seguras",'french_kiss'),
  row('es','Asunción',26,'femme','ES',"Artista visual en residencia internacional","Pelo azul, ropa sin manchas casi, mirada vivaz",'hug'),
  row('es','Milagros',23,'femme','ES',"Estudiante de idiomas, habla todo menos inglés","Libro de frases, sonrisa abierta, aire juguetón",'hug'),
  row('es','Nieves',29,'femme','ES',"Nutricionista recorriendo mercados locales","Bolsa de tela, lista de la compra, sonrisa saludable",'french_kiss'),
  row('es','Socorro',45,'femme','ES',"Directora de marketing tomando un respiro","Maletín relajado, teléfono casi apagado, sonrisa real",'hug'),
  row('es','Visitación',33,'femme','ES',"Bióloga marina en campo","Jersey azul, prismáticos, pelo recogido",'hug'),
  row('es','Carlos',26,'homme','ES',"Mochilero entre estaciones, libre","Jersillo marinero, vaqueros deshilachados, pelo revuelto",'hug'),
  row('es','Pablo',30,'homme','ES',"Desarrollador web en workation","Camiseta blanca, chaqueta ligera, mochila tech",'french_kiss'),
  row('es','Javier',24,'homme','ES',"Erasmus estudiante, primer viaje solo","Sudadera con capucha, vaqueros pitillo, zapatillas rojas",'hug'),
  row('es','Alejandro',33,'homme','ES',"Fotorreportero, siempre en tránsito","Chaqueta militar, cámara pesada, gafas de sol",'french_kiss'),
  row('es','Sergio',28,'homme','ES',"Músico rock entre conciertos","Guitarra al hombro, chupa de cuero, look vivido",'hug'),
  row('es','Roberto',22,'homme','ES',"Estudiante de bachillerato en road trip","Camiseta de concierto, vaqueros rotos, energía desbordante",'hug'),
  row('es','Miguel',36,'homme','ES',"Chef con estrella de vacaciones anónimas","Ropa casual, manos seguras, paladar refinado",'french_kiss'),
  row('es','Rodrigo',31,'homme','ES',"Periodista deportivo en trasfondo","Chaleco reportero, cuaderno, ojo rápido",'hug'),
  row('es','Óscar',27,'homme','ES',"Diseñador gráfico freelance","Chaqueta colorida, bolsa con lápices, pelo largo",'french_kiss'),
  row('es','Enrique',40,'homme','ES',"Arquitecto buscando inspiración urbana","Gafas de vista, carpeta de dibujos, paso curioso",'hug'),
  row('es','Antonio',45,'homme','ES',"Empresario queriendo de verdad desconectar","Look business-casual, reloj bonito, sonrisa poco frecuente pero verdadera",'hug'),
  row('es','Ignacio',38,'homme','ES',"Director de documentales siempre de camino","Chaleco técnico, micrófono de solapa, mirada atenta",'french_kiss'),
  row('es','Nacho',29,'homme','ES',"Entrenador personal en vacaciones merecidas","Físico atlético, ropa deportiva, energía positiva",'hug'),
  row('es','Marcos',23,'homme','ES',"Artista callejero en residencia","Ropa manchada de pintura, lienzo, aura creativa",'french_kiss'),
  row('es','Iñaki',35,'homme','ES',"Médico de cabecera recargando las pilas","Chándal cómodo, mirada tranquilizadora, paso sereno",'hug'),
  row('es','Álvaro',43,'homme','ES',"Director creativo entre dos campañas","Look cuidado pero relajado, portfolio bajo el brazo",'hug'),
  row('es','David',26,'homme','ES',"Marino en tierra firme unos días","Sudadera náutica, piel bronceada, manos fuertes",'french_kiss'),
  row('es','Fernando',32,'homme','ES',"Profesor universitario en congreso internacional","Chaqueta académica, bolsa de libros, aire distante pero agradable",'hug'),
  row('es','Adrián',29,'homme','ES',"Cocinero de street food, siempre en movimiento","Delantal de campo, bolsa de especias, buen rollo",'french_kiss'),
  row('es','Guillermo',50,'homme','ES',"Padre solo redescubriendo la libertad de viajar","Chaqueta práctica, sonrisa abierta, mirada serena",'hug'),
  row('es','Ramón',48,'homme','ES',"Piloto en escala de 8 horas","Uniforme desabrochado, maleta piloto, cansancio elegante",'hug'),
  row('es','Francisco',55,'homme','ES',"Jubilado dinámico, Europa en tren","Sombrero de viaje, mochila ligera, paso firme",'hug'),
  row('es','Paco',41,'homme','ES',"Ingeniero civil en inspección","Casco en la mochila, botas robustas, aire técnico",'french_kiss'),
  row('es','Emilio',37,'homme','ES',"Pastelero en ferias internacionales","Manos delicadas, maletín de herramientas, nariz fina",'hug'),
  row('es','Salvador',46,'homme','ES',"Pescador deportivo de excursión cultural","Botas de agua, aire sereno, ganas de hablar",'hug'),
  row('es','Manuel',34,'homme','ES',"Veterinario en conferencia científica","Mochila profesional, aire calmado, ama a todos los animales",'french_kiss'),
  row('es','Jesús',29,'homme','ES',"Bombero de guardia, tranquilo y reconfortante","Físico sólido, ropa sencilla, mirada serena",'hug'),
  row('es','Pepe',43,'homme','ES',"Director de marketing huyendo del comité","Traje relajado, teléfono apagado casi, sonrisa verdadera",'hug'),
  row('es','Gonzalo',27,'homme','ES',"Auxiliar de vuelo en escala improvisada","Uniforme, trolley de cabina, ligeramente jet-lagged",'french_kiss'),
  row('es','Tomás',31,'homme','ES',"Cocinero de comida callejera","Delantal de campo, bolsa de especias, entusiasmo culinario",'hug'),
  row('es','Adolfo',60,'homme','ES',"Viudo que redescubre la vida a los 60","Ropa limpia, mirada tímida pero cálida",'hug'),
  row('es','Modesto',53,'homme','ES',"Jubilado activo que recorre Europa en tren","Sombrero de andanzas, mochila ligera, paso seguro",'hug'),
  row('es','Alex',27,'non-binaire','ES',"Artista performativo entre géneros y fronteras","Ropa andrógina, joyas étnicas, sonrisa traviesa",'hug'),
  row('es','Samu',24,'non-binaire','ES',"Músico electrónico de gira europea","Auriculares grandes, chaqueta técnica, aire tranquilo",'french_kiss'),
  row('es','Gabi',30,'non-binaire','ES',"Terapeuta holístico en viaje interior","Ropa natural amplia, piedras en el cuello, calma irradiante",'hug'),
  row('es','Camilo',26,'non-binaire','ES',"Ilustrador·a en residencia artística","Cuaderno de bocetos, chaqueta oversize, gafas gruesas",'hug'),
  row('es','Dani',28,'non-binaire','ES',"Activista cultural siempre en marcha","Bolso bandolera, chapas militantes, mirada viva",'french_kiss'),
  row('es','Lucas',26,'non-binaire','ES',"Performer callejero en residencia artística","Pantalones anchos, chaqueta bordada, pelo de colores",'french_kiss'),
  row('es','Toni',25,'non-binaire','ES',"Bailarín·a contemporáneo·a de gira","Cuerpo siempre en movimiento, ropa amplia",'hug'),
  row('es','Peri',31,'non-binaire','ES',"Guionista, observa todo","Abrigo largo, pluma detrás de la oreja, sonrisa soñadora",'hug'),
  row('es','Zef',33,'non-binaire','ES',"Compositor·a electrónico·a entre directos","Auriculares de estudio, chaqueta técnica, paso rítmico",'french_kiss'),
  row('es','Miró',27,'non-binaire','ES',"Videomaker documentalista","Chaqueta técnica, micrófono de solapa visible, mirada atenta",'hug'),
];

// ── EN ──────────────────────────────────────────────────────────────────────
const en = [
  row('en','Emma',26,'femme','GB',"Solo traveller between projects, open to real connections","Brown hair, red jacket, hiking backpack",'hug'),
  row('en','Olivia',29,'femme','GB',"Freelance photographer always on the move","Camera around neck, jeans, curious eyes",'french_kiss'),
  row('en','Ava',24,'femme','GB',"Erasmus student discovering Europe solo","Blonde hair, uni hoodie, colourful trainers",'hug'),
  row('en','Grace',32,'femme','GB',"Architect seeking urban inspiration","Designer glasses, white coat, sketchbook",'french_kiss'),
  row('en','Poppy',27,'femme','GB',"Nurse on a well-deserved holiday","Sporty look, backpack, relaxed smile",'hug'),
  row('en','Lily',31,'femme','GB',"Journalist on the road for a story","Olive trench, yellow notebook, wavy hair",'hug'),
  row('en','Mia',23,'femme','GB',"Gap year after uni, exploring everything","Huge rucksack, worn-out shoes, pure energy",'french_kiss'),
  row('en','Freya',28,'femme','GB',"Graphic designer in workation mode","MacBook, colourful headphones, minimalist look",'hug'),
  row('en','Isla',34,'femme','GB',"Doctor on a research trip","Practical bag, attentive gaze, calm manner",'hug'),
  row('en','Rosie',25,'femme','GB',"Musician on tour","Instrument on her back, bohemian look, easy smile",'french_kiss'),
  row('en','Chloe',30,'femme','GB',"Marketing manager escaping spreadsheets","Loosened blazer, trolley case, genuine smile",'hug'),
  row('en','Harriet',36,'femme','GB',"Yoga teacher on a spiritual journey","Natural-toned clothes, yoga mat, serenity",'hug'),
  row('en','Arabella',22,'femme','GB',"Art history student, first solo adventure","Art book, vintage glasses, quiet wonder",'french_kiss'),
  row('en','Isobel',29,'femme','GB',"Therapist between seminars","Soft clothing, healing stones, gentle energy",'hug'),
  row('en','Tilly',35,'femme','GB',"Film director on location scouting","Technical vest, clipboard, sharp focus",'french_kiss'),
  row('en','Felicity',40,'femme','GB',"Consultant finally switching off","Crumpled blazer, suitcase, genuinely tired but warm",'hug'),
  row('en','Phoebe',26,'femme','GB',"Contemporary dancer on European tour","Always moving, wide trousers, high bun",'hug'),
  row('en','Beatrice',33,'femme','GB',"Biologist doing field research","Field gear, binoculars, hair in a ponytail",'french_kiss'),
  row('en','Imogen',38,'femme','GB',"Barrister on a proper holiday","Elegant but relaxed look, leather bag",'hug'),
  row('en','Nell',27,'femme','GB',"Aid worker between deployments","Functional clothing, bracelets from everywhere",'hug'),
  row('en','Verity',44,'femme','GB',"Secondary school teacher on a study trip","Knit jumper, notepad, sharp mind",'french_kiss'),
  row('en','Margot',37,'femme','GB',"Town planner scouting a new project","Technical map, pen behind ear, thoughtful look",'hug'),
  row('en','Patricia',48,'femme','GB',"Early retiree exploring Europe by train","Elegant grey hair, colourful raincoat, great mood",'hug'),
  row('en','Sabine',52,'femme','GB',"Writer gathering material","Oversized coat, pen always at hand, observant",'french_kiss'),
  row('en','Miriam',45,'femme','GB',"Head teacher on an educational visit","Professional bag, kind gaze, smart-casual outfit",'hug'),
  row('en','Dorothy',58,'femme','GB',"Active retiree seeing Europe alone at last","Short elegant grey hair, practical waterproof",'hug'),
  row('en','Pamela',50,'femme','GB',"Housewife finally travelling for herself","Embroidered bag, look of quiet wonder",'hug'),
  row('en','Agnes',39,'femme','GB',"Solicitor discovering slow travel","Quality handbag, unusually relaxed look",'french_kiss'),
  row('en','Frances',44,'femme','GB',"GP at an international conference","Conference badge, medical bag, reassuring smile",'hug'),
  row('en','Edith',47,'femme','GB',"Ceramicist hunting for new clay","Clay-stained hands, apron, creative aura",'hug'),
  row('en','Maureen',53,'femme','GB',"Retired tour guide enjoying a free day","Confident stride, total knowledge of the city, visible relief",'french_kiss'),
  row('en','Beverley',36,'femme','GB',"Amateur runner at city marathons","Running shoes, GPS watch, fit physique",'hug'),
  row('en','Glenda',42,'femme','GB',"Historical novelist seeking atmosphere","Vintage dress, notes notebook, dreamy air",'hug'),
  row('en','Shirley',31,'femme','GB',"Physiotherapist at a professional congress","Technical backpack, tracksuit, sure hands",'french_kiss'),
  row('en','Tracey',26,'femme','GB',"Visual artist at an international residency","Blue hair, mostly clean clothes, lively gaze",'hug'),
  row('en','Wendy',23,'femme','GB',"Language student who speaks everything except French","Phrasebook, open smile, playful air",'hug'),
  row('en','Sandra',29,'femme','GB',"Nutritionist touring local markets","Canvas tote, shopping list, healthy grin",'french_kiss'),
  row('en','Brenda',45,'femme','GB',"Marketing director taking a breather","Relaxed briefcase, phone almost off, real smile",'hug'),
  row('en','Gillian',33,'femme','GB',"Marine biologist in the field","Navy jumper, binoculars, hair tied back",'hug'),
  row('en','Kerry',27,'femme','GB',"Social media photographer, quieter than you'd think","Polished but approachable, phone always ready",'hug'),
  row('en','Jack',27,'homme','GB',"Backpacker between seasons, free as the wind","Navy jumper, frayed jeans, dishevelled hair",'hug'),
  row('en','Oliver',30,'homme','GB',"Software developer on workation","White tee, light jacket, tech backpack",'french_kiss'),
  row('en','Harry',24,'homme','GB',"Student on first solo trip","Hoodie, slim jeans, red trainers",'hug'),
  row('en','George',33,'homme','GB',"Photo journalist always in transit","Military jacket, heavy camera, sunglasses",'french_kiss'),
  row('en','Alfie',28,'homme','GB',"Musician between gigs, chasing energy","Grey beanie, acoustic guitar, denim jacket",'hug'),
  row('en','Charlie',35,'homme','GB',"Engineer on project holiday","Polo shirt, chinos, simple watch",'hug'),
  row('en','Finn',22,'homme','GB',"Sixth-former on first road trip","Concert tee, ripped jeans, boundless energy",'french_kiss'),
  row('en','Rory',38,'homme','GB',"Head chef on an anonymous break","Casual wear, confident hands, refined palate",'hug'),
  row('en','Jamie',31,'homme','GB',"Sports journalist abroad","Reporter vest, notepad, quick eye",'hug'),
  row('en','Toby',27,'homme','GB',"Freelance illustrator, drawing everywhere","Colourful jacket, bag of pencils, long hair",'french_kiss'),
  row('en','Hugo',40,'homme','GB',"Architect seeking urban inspiration","Designer glasses, drawing folder, curious stride",'hug'),
  row('en','Rupert',45,'homme','GB',"Entrepreneur genuinely trying to unwind","Business-casual, nice watch, rare but real smile",'hug'),
  row('en','Alastair',38,'homme','GB',"Documentary director always en route","Technical vest, lapel mic, attentive gaze",'french_kiss'),
  row('en','Callum',29,'homme','GB',"Personal trainer on a well-earned holiday","Athletic build, sportswear, positive energy",'hug'),
  row('en','Liam',23,'homme','GB',"Street artist in residence","Paint-splattered clothes, canvas, creative aura",'french_kiss'),
  row('en','Dominic',35,'homme','GB',"GP recharging his batteries","Comfortable hoodie, reassuring gaze, steady pace",'hug'),
  row('en','Tristan',43,'homme','GB',"Creative director between campaigns","Polished but relaxed look, portfolio under arm",'hug'),
  row('en','Crispin',26,'homme','GB',"Sailor on dry land for a few days","Sailing sweatshirt, tanned skin, strong hands",'french_kiss'),
  row('en','Miles',32,'homme','GB',"University lecturer at an international conference","Academic jacket, bag of books, distant-but-likeable air",'hug'),
  row('en','Leo',29,'homme','GB',"Street food cook, always on the move","Field apron, spice bag, infectious enthusiasm",'french_kiss'),
  row('en','William',50,'homme','GB',"Single dad rediscovering the freedom of travel","Practical jacket, open smile, serene eyes",'hug'),
  row('en','Theo',54,'homme','GB',"Airline pilot on an 8-hour layover","Unbuttoned uniform, pilot case, elegant fatigue",'hug'),
  row('en','Derek',57,'homme','GB',"Retired explorer, Europe by train","Travel hat, light rucksack, confident stride",'hug'),
  row('en','Keith',42,'homme','GB',"Civil engineer on site inspection","Helmet in bag, sturdy boots, technical air",'french_kiss'),
  row('en','Nigel',39,'homme','GB',"Pastry chef at international fairs","Delicate hands, tool case, fine nose",'hug'),
  row('en','Rod',47,'homme','GB',"Sport fisherman on a cultural day trip","Wellies, serene air, love of a good chat",'hug'),
  row('en','Clive',35,'homme','GB',"Vet at a scientific conference","Professional rucksack, calm air, loves every animal",'french_kiss'),
  row('en','Stu',30,'homme','GB',"Firefighter off duty, steady and reassuring","Solid build, simple jacket, composed gaze",'hug'),
  row('en','Barry',44,'homme','GB',"Marketing director fleeing the boardroom","Relaxed suit, phone almost off, genuine smile",'hug'),
  row('en','Gary',28,'homme','GB',"Flight attendant on an unplanned layover","Uniform, cabin trolley, slightly jet-lagged but friendly",'french_kiss'),
  row('en','Leon',32,'homme','GB',"Street food chef, always moving","Field apron, spice bag, culinary enthusiasm",'hug'),
  row('en','Norman',60,'homme','GB',"Widower rediscovering life at 60","Clean jacket, shy but warm gaze",'hug'),
  row('en','Trevor',53,'homme','GB',"Active retiree touring Europe by train","Travel hat, light rucksack, confident step",'hug'),
  row('en','Quinn',27,'non-binaire','GB',"Performance artist across genres and borders","Androgynous outfit, ethnic jewellery, mischievous smile",'hug'),
  row('en','River',24,'non-binaire','GB',"Electronic musician on European tour","Large headphones, technical jacket, calm air",'french_kiss'),
  row('en','Sage',31,'non-binaire','GB',"Holistic therapist on an inner journey","Wide natural clothing, stones at the neck, radiating calm",'hug'),
  row('en','Blake',28,'non-binaire','GB',"Illustrator passing through, observing everything","Sketchbook, oversized jacket, thick glasses",'hug'),
  row('en','Remy',30,'non-binaire','GB',"Cultural activist always in motion","Shoulder bag, activist pins, alert gaze",'french_kiss'),
  row('en','Kai',27,'non-binaire','GB',"Street performer in artistic residency","Wide trousers, embroidered jacket, colourful hair",'french_kiss'),
  row('en','Ash',26,'non-binaire','GB',"Contemporary dancer on tour","Always in motion, loose clothing",'hug'),
  row('en','Fern',32,'non-binaire','GB',"Screenwriter, observes everything","Oversized coat, pen behind ear, dreamy smile",'hug'),
  row('en','Zola',34,'non-binaire','GB',"Electronic composer between live sets","Studio headphones, technical jacket, rhythmic step",'french_kiss'),
  row('en','Marlo',28,'non-binaire','GB',"Documentary videomaker","Technical jacket, visible lapel mic, attentive look",'hug'),
];

// ── EE ──────────────────────────────────────────────────────────────────────
const ee = [
  // PL femmes
  row('ee','Agnieszka',26,'femme','PL',"Podróżuję sama między projektami, otwarta na prawdziwe spotkania","Brązowe włosy, czerwona kurtka, plecak turystyczny",'hug'),
  row('ee','Karolina',29,'femme','PL',"Fotografka na wyjeździe","Aparat na szyi, jeansy, ciekawy wzrok",'french_kiss'),
  row('ee','Magda',24,'femme','PL',"Studentka Erasmus, odkrywam Europę sama","Blond włosy, bluza z kapturem, kolorowe adidasy",'hug'),
  row('ee','Ola',32,'femme','PL',"Architektka szukająca inspiracji","Okulary od projektanta, biały płaszcz, szkicownik",'french_kiss'),
  row('ee','Kasia',27,'femme','PL',"Pielęgniarka na zasłużonych wakacjach","Sportowy look, plecak, rozluźniony uśmiech",'hug'),
  row('ee','Zosia',31,'femme','PL',"Dziennikarka szukająca historii","Zielony trencz, żółty notatnik, kręcone włosy",'hug'),
  row('ee','Nina',23,'femme','PL',"Przerwa rok po maturze, odkrywam wszystko","Ogromny plecak, znoszone buty, czysta energia",'french_kiss'),
  row('ee','Marta',28,'femme','PL',"Graficzka w trybie workation","MacBook, kolorowe słuchawki, minimalistyczny look",'hug'),
  row('ee','Ewa',34,'femme','PL',"Lekarka w podróży badawczej","Praktyczna torba, uważny wzrok, spokojny sposób bycia",'hug'),
  row('ee','Hania',25,'femme','PL',"Muzyczka w trasie","Instrument na plecach, look bohème, łatwy uśmiech",'french_kiss'),
  row('ee','Beata',30,'femme','PL',"Menadżerka marketingu uciekająca od tabelek","Rozluźniony blezer, walizka, prawdziwy uśmiech",'hug'),
  row('ee','Dominika',36,'femme','PL',"Nauczycielka jogi w podróży duchowej","Naturalne ubrania, matka do jogi, spokój",'hug'),
  row('ee','Monika',22,'femme','PL',"Studentka historii sztuki, pierwsza solowa przygoda","Książka o sztuce, okulary vintage, ciche zdziwienie",'french_kiss'),
  row('ee','Aleksandra',29,'femme','PL',"Terapeutka między seminariami","Miękkie ubrania, kamienie lecznicze, delikatna energia",'hug'),
  row('ee','Weronika',35,'femme','PL',"Reżyserka na zwiadzie lokacji","Kamizelka techniczna, clipboard, ostry wzrok",'french_kiss'),
  row('ee','Basia',40,'femme','PL',"Konsultantka wreszcie wyłączona","Zmięty blezer, walizka, naprawdę zmęczona ale ciepła",'hug'),
  row('ee','Natalia',26,'femme','PL',"Tancerka współczesna w tournée","Zawsze w ruchu, szerokie spodnie, kok",'hug'),
  row('ee','Patrycja',33,'femme','PL',"Biologka na badaniach terenowych","Wyposażenie terenowe, lornetka, włosy w kucyku",'french_kiss'),
  row('ee','Roksana',38,'femme','PL',"Prawniczka na prawdziwych wakacjach","Elegancki ale swobodny look, skórzana torebka",'hug'),
  row('ee','Sylwia',27,'femme','PL',"Pracownica humanitarna między misjami","Funkcjonalne ubrania, bransoletki z całego świata",'hug'),
  // CZ femmes
  row('ee','Kristýna',25,'femme','CZ',"Cestuji sama, hledám opravdová setkání","Hnědé vlasy, červená bunda, turistický batoh",'hug'),
  row('ee','Tereza',28,'femme','CZ',"Fotografka na výletě","Foťák na krku, džíny, zvídavý pohled",'french_kiss'),
  row('ee','Markéta',31,'femme','CZ',"Architekta hledá inspiraci","Designové brýle, bílý kabát, skicák",'hug'),
  row('ee','Lucie',24,'femme','CZ',"Erasmus studentka v Evropě","Blond vlasy, mikina, barevné tenisky",'french_kiss'),
  row('ee','Petra',29,'femme','CZ',"Zdravotní sestra na zasloužené dovolené","Sportovní look, batoh, uvolněný úsměv",'hug'),
  row('ee','Veronika',34,'femme','CZ',"Terapeutka mezi semináři","Měkké oblečení, léčivé kameny, jemná energie",'hug'),
  row('ee','Klára',22,'femme','CZ',"Meziroční přestávka po maturitě","Obrovský batoh, opotřebované boty, čistá energie",'french_kiss'),
  row('ee','Anežka',30,'femme','CZ',"Hudebnice na turné","Nástroj na zádech, bohémský vzhled, snadný úsměv",'hug'),
  row('ee','Šárka',26,'femme','CZ',"Grafická designérka v pracovním módu","MacBook, barevná sluchátka, minimalistický vzhled",'hug'),
  row('ee','Bára',35,'femme','CZ',"Novinářka hledá příběh","Zelený plášť, žlutý zápisník, kudrnaté vlasy",'french_kiss'),
  // HU femmes
  row('ee','Eszter',25,'femme','HU',"Egyedül utazom projektek között","Barna haj, piros dzseki, túrahátizsák",'hug'),
  row('ee','Réka',28,'femme','HU',"Szabadúszó fotós, mindig úton","Kamera a nyakán, farmer, kíváncsi tekintet",'french_kiss'),
  row('ee','Boglárka',31,'femme','HU',"Építész inspirációt keres","Designer szemüveg, fehér kabát, vázlatfüzet",'hug'),
  row('ee','Ágnes',24,'femme','HU',"Erasmus hallgató Európában","Szőke haj, kapucnis pulóver, színes edzőcipő",'french_kiss'),
  row('ee','Katalin',29,'femme','HU',"Nővér megérdemelt szabadságon","Sportos megjelenés, hátizsák, lazított mosoly",'hug'),
  row('ee','Nóra',34,'femme','HU',"Terapeuta szemináriumok között","Puha ruha, gyógyító kövek, szelíd energia",'hug'),
  row('ee','Zsuzsanna',22,'femme','HU',"Érettségi utáni rés év, mindent felfedezek","Hatalmas hátizsák, elnyűtt cipő, tiszta energia",'french_kiss'),
  row('ee','Viki',30,'femme','HU',"Zenész turnén","Hangszer a háton, bohém stílus, könnyed mosoly",'hug'),
  row('ee','Dóra',26,'femme','HU',"Grafikai tervező workation módban","MacBook, színes fejhallgató, minimalista stílus",'hug'),
  row('ee','Piroska',35,'femme','HU',"Újságíró történetet keres","Zöld kabát, sárga notesz, göndör haj",'french_kiss'),
  row('ee','Mária',29,'femme','HU',"Orvos kutatóúton","Praktikus táska, figyelmes tekintet, nyugodt modor",'hug'),
  row('ee','Zsófia',33,'femme','HU',"Jóga oktató szellemi utazáson","Természetes ruha, jógaszőnyeg, derű",'hug'),
  row('ee','Judit',40,'femme','HU',"Üzleti tanácsadó aki végre kikapcsol","Gyűrött blézer, bőrönd, igazán fáradt de meleg",'hug'),
  row('ee','Anna',27,'femme','HU',"Segélymunkás bevetések között","Funkcionális ruha, karkötők mindenhonnan",'hug'),
  row('ee','Erzsébet',44,'femme','HU',"Középiskolai tanár tanulmányúton","Kötött pulóver, notesz, éles elme",'french_kiss'),
  // PL hommes
  row('ee','Przemek',27,'homme','PL',"Plecakarz między sezonami, wolny jak wiatr","Granatowy sweter, postrzępione jeansy, potargane włosy",'hug'),
  row('ee','Bartek',30,'homme','PL',"Programista w trybie workation","Biała koszulka, lekka kurtka, plecak tech",'french_kiss'),
  row('ee','Michał',24,'homme','PL',"Student na pierwszej solowej wyprawie","Bluza z kapturem, wąskie jeansy, czerwone adidasy",'hug'),
  row('ee','Krzysztof',33,'homme','PL',"Fotoreporter zawsze w drodze","Wojskowa kurtka, ciężki aparat, okulary słoneczne",'french_kiss'),
  row('ee','Piotr',28,'homme','PL',"Muzyk rockowy między koncertami","Gitara na ramieniu, skórzana kurtka, przeżyty look",'hug'),
  row('ee','Adam',22,'homme','PL',"Uczeń na wyjeździe po maturze","Koszulka z koncertu, podarte jeansy, pełno energii",'hug'),
  row('ee','Grzegorz',36,'homme','PL',"Kucharz gwiazdkowy na anonimowych wakacjach","Casualowe ubrania, pewne ręce, wyrafinowane podniebienie",'french_kiss'),
  row('ee','Marcin',31,'homme','PL',"Dziennikarz sportowy na wyjeździe","Kamizelka reporterska, notatnik, szybkie oko",'hug'),
  row('ee','Tomek',27,'homme','PL',"Grafik freelance, rysuje wszędzie","Kolorowa kurtka, torba z ołówkami, długie włosy",'french_kiss'),
  row('ee','Jakub',40,'homme','PL',"Architekt szukający miejskiej inspiracji","Okulary korekcyjne, teczka rysunków, ciekawy krok",'hug'),
  row('ee','Marek',38,'homme','PL',"Reżyser dokumentalny zawsze w drodze","Kamizelka techniczna, widoczny mikrofon, uważne spojrzenie",'french_kiss'),
  row('ee','Paweł',29,'homme','PL',"Osobisty trener na zasłużonych wakacjach","Atletyczna sylwetka, odzież sportowa, pozytywna energia",'hug'),
  row('ee','Łukasz',23,'homme','PL',"Artysta uliczny na rezydencji","Ubrania poplamione farbą, płótno, twórcza aura",'french_kiss'),
  row('ee','Rafał',35,'homme','PL',"Lekarz ogólny ładujący baterie","Wygodna bluza, uspokajające spojrzenie, spokojny krok",'hug'),
  row('ee','Sławomir',43,'homme','PL',"Dyrektor kreatywny między kampaniami","Zadbany ale swobodny look, portfolio pod pachą",'hug'),
  // CZ hommes
  row('ee','Lukáš',27,'homme','CZ',"Batůžkář mezi sezónami","Námořnický svetr, roztřepené džíny, rozcuchané vlasy",'hug'),
  row('ee','Marek',30,'homme','CZ',"IT vývojář ve workation módu","Bílé tričko, lehká bunda, tech batoh",'french_kiss'),
  row('ee','Ondřej',24,'homme','CZ',"Student na první sólové cestě","Mikina, slim džíny, červené tenisky",'hug'),
  row('ee','Tomáš',33,'homme','CZ',"Fotoreportér vždy na cestách","Vojenská bunda, těžký foťák, sluneční brýle",'french_kiss'),
  row('ee','Pavel',28,'homme','CZ',"Rockový muzikant mezi koncerty","Kytara přes rameno, kožená bunda, prožitý vzhled",'hug'),
  row('ee','Jiří',36,'homme','CZ',"Šéfkuchař na anonymní dovolené","Casual oblečení, jisté ruce, vytříbené chutě",'french_kiss'),
  row('ee','Radek',29,'homme','CZ',"Sportovní novinář v zahraničí","Reportérská vesta, zápisník, rychlý pohled",'hug'),
  row('ee','Vojta',27,'homme','CZ',"Grafický designér na volné noze","Barevná bunda, taška s tužkami, dlouhé vlasy",'french_kiss'),
  row('ee','Martin',40,'homme','CZ',"Architekt hledá inspiraci","Designové brýle, složka s náčrty, zvídavý krok",'hug'),
  row('ee','Petr',35,'homme','CZ',"Lékař dobíjí baterie","Pohodlná mikina, uklidňující pohled, klidný krok",'hug'),
  // HU hommes
  row('ee','Ádám',27,'homme','HU',"Hátizsákos utazó szezonok között","Kék csíkos pulóver, kopott farmer, kócos haj",'hug'),
  row('ee','Péter',30,'homme','HU',"IT fejlesztő workation módban","Fehér póló, könnyű dzseki, tech hátizsák",'french_kiss'),
  row('ee','Bálint',24,'homme','HU',"Első szóló utazásán lévő hallgató","Kapucnis pulóver, szűk farmer, piros edzőcipő",'hug'),
  row('ee','Gábor',33,'homme','HU',"Fotóriporter mindig úton","Katonai dzseki, nehéz fényképezőgép, napszemüveg",'french_kiss'),
  row('ee','Zoltán',28,'homme','HU',"Rockzenész koncertek között","Gitár a vállán, bőrdzseki, megélt kinézet",'hug'),
  row('ee','Tibor',36,'homme','HU',"Séf névtelen vakáción","Casual ruha, biztos kezek, kifinomult ízlés",'french_kiss'),
  row('ee','Attila',31,'homme','HU',"Sportújságíró külföldön","Riporter mellény, notesz, gyors szem",'hug'),
  row('ee','László',27,'homme','HU',"Szabadúszó grafikus, mindenhol rajzol","Színes dzseki, ceruzás táska, hosszú haj",'french_kiss'),
  row('ee','Sándor',40,'homme','HU',"Építész városi inspirációt keres","Dizájn szemüveg, rajzmappa, kíváncsi lépések",'hug'),
  row('ee','Balázs',29,'homme','HU',"Személyi edző megérdemelt vakáción","Atlétikus alkat, sportruha, pozitív energia",'hug'),
  row('ee','István',53,'homme','HU',"Aktív nyugdíjas, Európa vonaton","Utazókalap, könnyű hátizsák, biztos lépés",'hug'),
  row('ee','János',60,'homme','HU',"Özvegy aki 60 évesen fedezi fel újra az életet","Tiszta kabát, félénk de meleg tekintet",'hug'),
  // Non-binaire mix
  row('ee','Kacper',26,'non-binaire','PL',"Artysta performatywny między granicami","Androgyniczne ubrania, etnyczna biżuteria, figlarski uśmiech",'hug'),
  row('ee','Remi',24,'non-binaire','PL',"Muzyk elektroniczny w europejskim tournée","Duże słuchawki, techniczna kurtka, spokojny wygląd",'french_kiss'),
  row('ee','Ren',30,'non-binaire','PL',"Holistyczny terapeuta w wewnętrznej podróży","Szerokie naturalne ubrania, kamienie na szyi, promieniejący spokój",'hug'),
  row('ee','Blanka',28,'non-binaire','PL',"Ilustrator-ka w artystycznej rezydencji","Szkicownik, oversizowa kurtka, grube okulary",'hug'),
  row('ee','Niko',31,'non-binaire','PL',"Aktywista-ka kulturalny-a zawsze w ruchu","Torba na ramię, odznaki aktywistyczne, bystry wzrok",'french_kiss'),
  row('ee','Zden',27,'non-binaire','CZ',"Performativní umělec mezi žánry","Androgynní oblečení, etnické šperky, škodolibý úsměv",'hug'),
  row('ee','Ríša',24,'non-binaire','CZ',"Elektronický muzikant na turné","Velká sluchátka, technická bunda, klidný vzduch",'french_kiss'),
  row('ee','Nela',30,'non-binaire','CZ',"Holistický terapeut na vnitřní cestě","Volné přírodní oblečení, kameny na krku, vyzařující klid",'hug'),
  row('ee','Sona',29,'non-binaire','CZ',"Ilustrátor-ka v umělecké rezidenci","Skicák, oversized bunda, silné brýle",'hug'),
  row('ee','Klim',31,'non-binaire','CZ',"Kulturní aktivista-ka vždy v pohybu","Taška přes rameno, aktivistické odznaky, bystré oči",'french_kiss'),
  row('ee','Rémi',27,'non-binaire','HU',"Performatív művész műfajok és határok között","Androgün ruha, etnikus ékszerek, huncut mosoly",'hug'),
  row('ee','Noel',24,'non-binaire','HU',"Elektronikus zenész európai turnén","Nagy fejhallgató, technikai dzseki, nyugodt megjelenés",'french_kiss'),
  row('ee','Ren',30,'non-binaire','HU',"Holisztikus terapeuta belső utazáson","Széles természetes ruha, kövek a nyakban, kisugárzó nyugalom",'hug'),
  row('ee','Soma',28,'non-binaire','HU',"Illusztrátor-nő művészeti rezidencián","Vázlatfüzet, oversized dzseki, vastag szemüveg",'hug'),
  row('ee','Niko',31,'non-binaire','HU',"Kulturális aktivista-nő mindig mozgásban","Válltáska, aktivista kitűzők, éber tekintet",'french_kiss'),
];

const blocks = [
  insertBlock('FR (1-100)', 'FR (1-100)', fr),
  insertBlock('IT (101-200)', 'IT (101-200)', it),
  insertBlock('DE (201-300)', 'DE (201-300)', de),
  insertBlock('ES (301-400)', 'ES (301-400)', es),
  insertBlock('EN (401-500)', 'EN (401-500)', en),
  insertBlock('EE (501-600)', 'EE (501-600)', ee),
];

fs.appendFileSync(path, blocks.join(''), 'utf8');

const total = fr.length + it.length + de.length + es.length + en.length + ee.length;
console.log('Total profiles inserted:', total);
